<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Establishes the initial Exchanging-owned rate and pair persistence schema.
 */
final class Version20260923213648 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the canonical Exchanging pair/rate tables, audit columns, and lookup indexes.';
    }

    public function up(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->abortIf(
            !$platform instanceof SQLitePlatform && !$platform instanceof PostgreSQLPlatform,
            'Exchanging migrations support SQLite and PostgreSQL only.',
        );

        if ($platform instanceof PostgreSQLPlatform) {
            $this->addSql('CREATE TABLE exchange_exchange (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency_code VARCHAR(3) NOT NULL, quote_currency_code VARCHAR(3) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE TABLE exchange_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, base_currency_code VARCHAR(3) NOT NULL, quote_currency_code VARCHAR(3) NOT NULL, rate_value NUMERIC(20, 10) NOT NULL, provider_code VARCHAR(80) NOT NULL, rate_date DATE NOT NULL, captured_at_immutable TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        } else {
            $this->addSql('CREATE TABLE exchange_exchange (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, base_currency_code VARCHAR(3) NOT NULL, quote_currency_code VARCHAR(3) NOT NULL, is_active BOOLEAN NOT NULL, created_at DATETIME NOT NULL, modified_at DATETIME DEFAULT NULL, created_by VARCHAR(190) DEFAULT NULL, modified_by VARCHAR(190) DEFAULT NULL)');
            $this->addSql('CREATE TABLE exchange_rate (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, base_currency_code VARCHAR(3) NOT NULL, quote_currency_code VARCHAR(3) NOT NULL, rate_value NUMERIC(20, 10) NOT NULL, provider_code VARCHAR(80) NOT NULL, rate_date DATE NOT NULL, captured_at_immutable DATETIME NOT NULL)');
        }

        $this->addSql('CREATE INDEX idx_exchange_pair ON exchange_exchange (base_currency_code, quote_currency_code)');
        $this->addSql('CREATE INDEX idx_exchange_rate_pair_date ON exchange_rate (base_currency_code, quote_currency_code, rate_date)');
        $this->addSql('CREATE INDEX idx_exchange_rate_provider_date ON exchange_rate (provider_code, rate_date)');
    }

    public function down(Schema $schema): void
    {
        $platform = $this->connection->getDatabasePlatform();
        $this->abortIf(
            !$platform instanceof SQLitePlatform && !$platform instanceof PostgreSQLPlatform,
            'Exchanging migrations support SQLite and PostgreSQL only.',
        );

        $this->addSql('DROP TABLE exchange_exchange');
        $this->addSql('DROP TABLE exchange_rate');
    }
}
