param(
    [Parameter(Mandatory = $true)]
    [string] $HostRoot,

    [Parameter(Mandatory = $false)]
    [string] $TargetFile = "config/packages/exchange_nbu_import.yaml",

    [Parameter(Mandatory = $false)]
    [string] $ExchangingRelativePath = "../Exchanging"
)

$ErrorActionPreference = "Stop"

function Assert-PathExists {
    param([Parameter(Mandatory = $true)][string] $PathValue, [Parameter(Mandatory = $true)][string] $Label)

    if (-not (Test-Path -LiteralPath $PathValue)) {
        throw "$Label does not exist: $PathValue"
    }
}

function Ensure-Directory {
    param([Parameter(Mandatory = $true)][string] $DirectoryPath)

    if (-not (Test-Path -LiteralPath $DirectoryPath)) {
        New-Item -ItemType Directory -Force -Path $DirectoryPath | Out-Null
    }
}

Assert-PathExists -PathValue $HostRoot -Label "HostRoot"

$targetPath = Join-Path $HostRoot $TargetFile
Ensure-Directory -DirectoryPath (Split-Path -Parent $targetPath)

if (Test-Path -LiteralPath $targetPath) {
    throw "Target import file already exists: $targetPath"
}

$content = @"
# Optional Exchanging NBU provider import.
# Generated by tools/host/exchanging-add-nbu-import-snippet.ps1.
imports:
  - { resource: '$ExchangingRelativePath/config/packages/exchange_nbu_provider.yaml' }
"@

Set-Content -LiteralPath $targetPath -Value $content -Encoding UTF8

Write-Host "Created optional NBU provider import: $targetPath"
Write-Host "Review path before committing: $ExchangingRelativePath/config/packages/exchange_nbu_provider.yaml"
